version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/app" 
    schedule:
      interval: "daily"
    target-branch: "dev"

  - package-ecosystem: "yarn"
    directory: "/app" 
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "/api" 
    schedule:
      interval: "daily"
    target-branch: "dev"

  - package-ecosystem: "pip"
    directory: "/api" 
    schedule:
      interval: "daily"
    target-branch: "main"
